/**
 * Generated by @proofgeist/fmdapi package
 * https://github.com/proofgeist/fmdapi
 * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
 */
import { z } from "zod";

// @generated
// prettier-ignore
/* eslint-disable */
export const ZNameCard = z.object({
	備考: z.string(),
	氏名カナ: z.string(),
	氏名: z.string(),
	敬称: z.string(),
	会社名カナ: z.string(),
	会社名: z.string(),
	部署名1: z.string(),
	部署名2_役職: z.string(),
	電話1: z.string(),
	電話2: z.string(),
	携帯電話: z.string(),
	Eﾒｰﾙ: z.string(),
	FAX: z.string(),
	携帯メール: z.string(),
	住所1: z.string(),
	住所2: z.string(),
	郵便番号: z.string(),
	URL: z.string(),
});

export type TNameCard = z.infer<typeof ZNameCard>;
