name = "slack-to-namecard-backend"
main = "src/index.ts"
compatibility_date = "2024-12-04"

compatibility_flags = ["nodejs_compat"]

workers_dev = false

[vars]
AZURE_OPENAI_API_VERSION = "2024-08-01-preview"
OPENAI_MODEL = "gpt-4o"

[[kv_namespaces]]
binding = "FM_TOKEN_KV"
id = "<Your KV Namespace ID>"

[observability]
enabled = true
