/**
 * [need configuration] fmp://<filemaker_host>/<filename>.fmp12
 */
const baseFmpUrl = "fmp://<filemaker_host>/<filename>.fmp12";

/**
 * [need configuration] specify script_name that searches records generated by Slack app. (For example, search with "修正者名")
 */
export const openFileUrl = `${baseFmpUrl}?script=<script_name>`;

/**
 * [need configuration] specify script_name that searches records with name.
 */
export const openFileWithNameUrl = (name: string) =>
	`${baseFmpUrl}?script=<script_name>&param=${encodeURIComponent(name)}`;
